### ISSUE TITLE
Alien-cmake3-0.06: no matching files in listing... on Strawberry Perl 5.30.3 64 bit

### ISSUE THREAD

**Issue by twata1** [PerlAlien/Alien-cmake3#13]
Hello,

It seems to me that cmake binary release name changes as of v3.20.
Currently, Windows x64 zip file name is cmake-3.21.0-windows-x86_64.zip.

Thank you,

**Comment by plicease** [comment]
Looks like the Linux tarball has changed name as well.  Thank you for reporting this.

**Comment by plicease** [comment]
This should be fixed in 0.07.  Please see if you find anything else amiss.
