### ISSUE TITLE
should download older cmake on Windows XP and Vista

### ISSUE THREAD

**Issue by chorny** [PerlAlien/Alien-cmake3#3]
cmake 3.14.x no longer supports Windows XP and Vista. 3.13 ( https://cmake.org/files/v3.13/cmake-3.13.4-win32-x86.zip ) does support them.

**Comment by plicease** [comment]
I might consider a non-invasive PR to do this. Neither Windows XP nor Vista are supported by Microsoft, I'm not entirely sure that it is a good idea.

**Comment by genio** [comment]
Win XP is dead since 2014. Let's not continue wasting time on a dead platform in the Perl world. You can't even install a proper web browser on Win XP anymore. It's a security concern for the world that we should not promote any longer.

**Comment by plicease** [comment]
I've added a caveats section which includes some hints for using `Alien::cmake3` on unsupported systems.
https://github.com/PerlAlien/Alien-cmake3#caveats
including a suggestion to not use unsupported operating systems if possible.
