### ISSUE TITLE
minimum cmake version

### ISSUE THREAD

**Issue by basiliscos** [PerlAlien/Alien-cmake3#4]
It is desirable somehow tell `alien::cmake3` the minimum required cmake version.  May be the `Alien::cmake3` version should simply match cmake version?

**Comment by plicease** [comment]
I agree this would be a desirable goal, but we want to use the system cmake when available and tracking tracking the latest version would force a share install too frequently, since most distros have cmake packages which are usually at least a couple versions behind.
